project_id = "vpinncisktmyarvaxxrm"

[auth]
enabled = true
site_url = "https://c7c34dbb-568f-47a0-bf07-6b0472a82d54.lovableproject.com"
additional_redirect_urls = ["https://vpinncisktmyarvaxxrm.supabase.co"]

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[edge_runtime]
enabled = true

[functions.geocode-address]
verify_jwt = false

[functions.analyze-roof]
verify_jwt = false

[functions.capture-satellite]
verify_jwt = false

[functions.process-validation-report]
verify_jwt = false

[functions.test-openai]
verify_jwt = false

[functions.test-openai-simple]
verify_jwt = false